[programs.localnet]
sol_blog = "BqNdYPtPNavi8KB59MXcndJ9yqTqeqBsDG3QVh1NGg3v"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rackham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
